### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by Jiarui-Zeng** [Jiarui-Zeng/Jiarui-Zeng.github.io#1]
[demo](https://github.com/zhangxinxu/quiz/issues/31)

**Comment by Jiarui-Zeng** [comment]
[demo](https://github.com/zhangxinxu/quiz/issues/31)

```html
<div class="btn-group">
  <button class="cus-btn">按钮</button>
</div>

<div class="btn-group">
  <button class="cus-btn">按钮</button>
  <button class="cus-btn">按钮</button>
</div>

<div class="btn-group">
  <button class="cus-btn">按钮</button>
  <button class="cus-btn">按钮</button>
  <button class="cus-btn">按钮</button>
</div>
```

```css
.btn-group {
  display: flex;
  flex-wrap: nowrap;
  padding: 0 0 1rem 1rem ;
  flex-shirnk: 1;
}
.cus-btn {
  flex: 1;
  margin-right: 1rem;
  color: red;
  border: 1px solid red;
  border-radius: 1em;
  background: transparent;
  white-space: nowrap;
}
```
